use crate::args::{CiModeArg, GithubCiArgs, SeverityArg};
use anyhow::{Context, Result, bail};
use regex::Regex;
use std::path::Path;
use std::sync::LazyLock;

const GENERATED_HEADER: &str = "# Generated by security-harness-kit. Regenerate with `shk ci init github --force`; manual edits will be overwritten.";

/// Accept `latest` or a SemVer-ish git tag (`v?MAJOR.MINOR.PATCH[-pre]`).
/// Refuses shell metacharacters so we never embed something hostile into the installer URL.
static SHK_VERSION_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^(latest|v?\d+\.\d+\.\d+(?:-[A-Za-z0-9.\-]+)?)$").unwrap());

/// Conservative path constraint: forward-slashed relative path, no `..` segments, no spaces.
static INSTALLER_NAME_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^[A-Za-z0-9._\-]+(?:/[A-Za-z0-9._\-]+)*$").unwrap());

/// `owner/repo` GitHub slug. Sufficient for the few characters GitHub allows in either segment.
static REPO_SLUG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^[A-Za-z0-9._\-]+/[A-Za-z0-9._\-]+$").unwrap());

/// Effective default when the user does not pass `--fail-on`. Documented in the CLI help
/// text on `GithubCiArgs::fail_on`; keep them in sync.
const DEFAULT_FAIL_ON: SeverityArg = SeverityArg::High;

pub fn init_github(root: &Path, args: GithubCiArgs) -> Result<()> {
    validate(&args)?;

    if matches!(args.mode, CiModeArg::Audit) && args.fail_on.is_some() {
        eprintln!(
            "warning: --fail-on is ignored when --mode audit (audit hooks always exit 0). \
             Drop --fail-on or switch to --mode blocking to make it effective."
        );
    }

    let workflow = github_workflow(&args);

    if args.dry_run {
        print!("{workflow}");
        return Ok(());
    }

    let dest = root.join(&args.output);
    if dest.exists() && !args.force {
        bail!(
            "{} already exists (use --force to overwrite)",
            dest.display()
        );
    }

    let parent = dest.parent().with_context(|| {
        format!(
            "workflow destination has no parent directory: {}",
            dest.display()
        )
    })?;
    std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    std::fs::write(&dest, workflow).with_context(|| format!("write {}", dest.display()))?;

    println!("Wrote GitHub Actions workflow to {}", dest.display());
    Ok(())
}

/// Reject `.` / `..` segments in any forward-slash separated path-like input.
/// Shared by `--repo` and `--installer-name` so neither can synthesise a URL that
/// escapes the intended GitHub release path.
fn has_traversal_segment(value: &str) -> bool {
    value
        .split('/')
        .any(|segment| segment == "." || segment == "..")
}

fn validate(args: &GithubCiArgs) -> Result<()> {
    if !REPO_SLUG_RE.is_match(&args.repo) || has_traversal_segment(&args.repo) {
        bail!(
            "invalid --repo `{}` (expected `owner/repository`)",
            args.repo
        );
    }
    if !SHK_VERSION_RE.is_match(&args.shk_version) {
        bail!(
            "invalid --shk-version `{}` (expected `latest` or `vMAJOR.MINOR.PATCH`)",
            args.shk_version
        );
    }
    if !INSTALLER_NAME_RE.is_match(&args.installer_name)
        || has_traversal_segment(&args.installer_name)
    {
        bail!(
            "invalid --installer-name `{}` (expected a relative path under the release assets)",
            args.installer_name
        );
    }
    // `--path` is embedded into a YAML block scalar (`run: |`). A literal newline
    // there breaks the scalar and produces an unparsable workflow file regardless
    // of how the value is shell-quoted.
    if args.path.contains('\n') || args.path.contains('\r') {
        bail!("invalid --path: must not contain newline or carriage return characters");
    }
    Ok(())
}

pub fn github_workflow(args: &GithubCiArgs) -> String {
    let installer_url = installer_url(&args.repo, &args.shk_version, &args.installer_name);
    let fail_on = args.fail_on.unwrap_or(DEFAULT_FAIL_ON);
    let scan_command = match args.mode {
        CiModeArg::Blocking => format!(
            "shk scan {} --json --fail-on {}",
            shell_quote(&args.path),
            fail_on.as_str()
        ),
        CiModeArg::Audit => format!("shk scan {} --json --audit", shell_quote(&args.path)),
    };

    format!(
        r#"{GENERATED_HEADER}
name: Security Harness Kit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: shk-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install shk
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf {installer_url} | sh

      - name: Run shk
        shell: bash
        run: |
          {scan_command}
"#
    )
}

fn installer_url(repo: &str, version: &str, installer_name: &str) -> String {
    let release_path = if version == "latest" {
        "latest/download".to_string()
    } else {
        format!("download/{version}")
    };
    format!("https://github.com/{repo}/releases/{release_path}/{installer_name}")
}

fn shell_quote(s: &str) -> String {
    if !s.is_empty()
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'/' | b'_' | b'-' | b':'))
    {
        return s.to_string();
    }
    format!("'{}'", s.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn args(mode: CiModeArg) -> GithubCiArgs {
        GithubCiArgs {
            mode,
            fail_on: None,
            path: ".".into(),
            repo: "Kazuki-tam/security-harness-kit".into(),
            shk_version: "latest".into(),
            installer_name: "shk-cli-installer.sh".into(),
            output: PathBuf::from(".github/workflows/shk.yml"),
            dry_run: false,
            force: false,
        }
    }

    #[test]
    fn github_workflow_uses_cargo_dist_installer() {
        let workflow = github_workflow(&args(CiModeArg::Blocking));

        assert!(workflow.contains("releases/latest/download/shk-cli-installer.sh"));
        assert!(workflow.contains("shk scan . --json --fail-on high"));
        assert!(workflow.contains("actions/checkout@v6"));
    }

    #[test]
    fn github_workflow_supports_audit_mode() {
        let workflow = github_workflow(&args(CiModeArg::Audit));

        assert!(workflow.contains("shk scan . --json --audit"));
        assert!(!workflow.contains("--fail-on"));
    }

    #[test]
    fn github_workflow_emits_minimal_permissions_and_concurrency() {
        let workflow = github_workflow(&args(CiModeArg::Blocking));

        assert!(workflow.contains("permissions:\n  contents: read"));
        assert!(workflow.contains("concurrency:"));
        assert!(workflow.contains("cancel-in-progress: true"));
        assert!(workflow.contains("group: shk-${{ github.workflow }}-${{ github.ref }}"));
    }

    #[test]
    fn installer_url_handles_pinned_version() {
        let url = installer_url(
            "Kazuki-tam/security-harness-kit",
            "v0.2.3",
            "shk-cli-installer.sh",
        );
        assert_eq!(
            url,
            "https://github.com/Kazuki-tam/security-harness-kit/releases/download/v0.2.3/shk-cli-installer.sh"
        );
    }

    #[test]
    fn shell_quote_handles_spaces_and_quotes() {
        assert_eq!(shell_quote("src fixtures"), "'src fixtures'");
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn shell_quote_wraps_newline_input_but_validate_rejects_it() {
        // shell_quote on its own would happily produce a multi-line single-quoted string.
        // That is fine for a shell, but it would corrupt the surrounding YAML block scalar,
        // so `validate` must reject newline input before we ever quote it.
        let quoted = shell_quote("src\nevil");
        assert!(quoted.contains('\n'), "{quoted}");

        let mut a = args(CiModeArg::Blocking);
        a.path = "src\nevil".into();
        let err = validate(&a).unwrap_err();
        assert!(err.to_string().contains("must not contain newline"));

        a.path = "src\rdir".into();
        let err = validate(&a).unwrap_err();
        assert!(err.to_string().contains("must not contain newline"));
    }

    #[test]
    fn github_workflow_quotes_path_with_whitespace() {
        let mut a = args(CiModeArg::Blocking);
        a.path = "src dir".into();
        let workflow = github_workflow(&a);
        assert!(
            workflow.contains("shk scan 'src dir' --json --fail-on high"),
            "{workflow}"
        );
    }

    #[test]
    fn validate_rejects_unsafe_inputs() {
        let mut a = args(CiModeArg::Blocking);
        a.repo = "not-a-slug".into();
        assert!(validate(&a).is_err());

        let mut a = args(CiModeArg::Blocking);
        a.repo = "../foo".into();
        assert!(
            validate(&a).is_err(),
            "`..` segments must be rejected even when REPO_SLUG_RE matches"
        );

        let mut a = args(CiModeArg::Blocking);
        a.repo = "owner/..".into();
        assert!(validate(&a).is_err());

        let mut a = args(CiModeArg::Blocking);
        a.shk_version = "; rm -rf /".into();
        assert!(validate(&a).is_err());

        let mut a = args(CiModeArg::Blocking);
        a.installer_name = "../etc/passwd".into();
        assert!(validate(&a).is_err());
    }

    #[test]
    fn validate_accepts_canonical_inputs() {
        let mut a = args(CiModeArg::Blocking);
        a.shk_version = "v0.2.3".into();
        a.installer_name = "nested/asset.sh".into();
        assert!(validate(&a).is_ok());
    }
}
