use crate::args::{CiModeArg, GithubCiArgs, SeverityArg};
use crate::{fs_atomic, safety};
use anyhow::{Context, Result, bail};
use regex::Regex;
use std::path::Path;
use std::sync::LazyLock;

const GENERATED_HEADER: &str = "# Generated by shk. Regenerate with `shk ci init github --force`; manual edits will be overwritten.";

/// GitHub-owned checkout action; keep this on the current major for maintainability.
const CHECKOUT_ACTION: &str = "actions/checkout@v6";
/// GitHub-owned SARIF uploader; keep this on the current supported major.
const CODEQL_UPLOAD_ACTION: &str = "github/codeql-action/upload-sarif@v4";

/// Accept `latest` or a SemVer-ish git tag (`v?MAJOR.MINOR.PATCH[-pre]`).
/// Refuses shell metacharacters so we never embed something hostile into the installer URL.
static SHK_VERSION_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^(latest|v?\d+\.\d+\.\d+(?:-[A-Za-z0-9.\-]+)?)$").unwrap());

/// `owner/repo` GitHub slug. Sufficient for the few characters GitHub allows in either segment.
static REPO_SLUG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^[A-Za-z0-9._\-]+/[A-Za-z0-9._\-]+$").unwrap());

/// Effective default when the user does not pass `--fail-on`. Documented in the CLI help
/// text on `GithubCiArgs::fail_on`; keep them in sync.
const DEFAULT_FAIL_ON: SeverityArg = SeverityArg::High;

pub fn init_github(root: &Path, args: GithubCiArgs) -> Result<()> {
    validate(&args)?;

    if matches!(args.mode, CiModeArg::Audit) && args.fail_on.is_some() {
        eprintln!(
            "warning: --fail-on is ignored when --mode audit (audit scans do not fail on findings). \
             Drop --fail-on or switch to --mode blocking to make it effective."
        );
    }

    let workflow = github_workflow(&args);

    if args.dry_run {
        print!("{workflow}");
        return Ok(());
    }

    let dest = root.join(&args.output);
    safety::ensure_write_path_within(root, &dest)?;
    if dest.exists() && !args.force {
        bail!(
            "{} already exists (use --force to overwrite)",
            dest.display()
        );
    }

    let parent = dest.parent().with_context(|| {
        format!(
            "workflow destination has no parent directory: {}",
            dest.display()
        )
    })?;
    std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    fs_atomic::write_atomic(&dest, workflow.as_bytes())
        .with_context(|| format!("write {}", dest.display()))?;

    println!("Wrote GitHub Actions workflow to {}", dest.display());
    Ok(())
}

/// Reject `.` / `..` segments in forward-slash separated inputs.
fn has_traversal_segment(value: &str) -> bool {
    value
        .split('/')
        .any(|segment| segment == "." || segment == "..")
}

fn validate(args: &GithubCiArgs) -> Result<()> {
    if !REPO_SLUG_RE.is_match(&args.repo) || has_traversal_segment(&args.repo) {
        bail!(
            "invalid --repo `{}` (expected `owner/repository`)",
            args.repo
        );
    }
    if !SHK_VERSION_RE.is_match(&args.shk_version) {
        bail!(
            "invalid --shk-version `{}` (expected `latest` or `vMAJOR.MINOR.PATCH`)",
            args.shk_version
        );
    }
    // `--path` is embedded into a YAML block scalar (`run: |`). A literal newline
    // there breaks the scalar and produces an unparsable workflow file regardless
    // of how the value is shell-quoted.
    if args.path.contains('\n') || args.path.contains('\r') {
        bail!("invalid --path: must not contain newline or carriage return characters");
    }
    Ok(())
}

pub fn github_workflow(args: &GithubCiArgs) -> String {
    let install_script = verified_install_script(&args.repo, &args.shk_version);
    let permissions = workflow_permissions(args.upload_sarif);
    let scan_steps = workflow_scan_steps(args);

    format!(
        r#"{GENERATED_HEADER}
name: Security Harness Kit

on:
  pull_request:
  push:
    branches: [main]

permissions:
{permissions}

concurrency:
  group: shk-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT_ACTION} # v6
        with:
          persist-credentials: false

      - name: Install shk
        shell: bash
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
{install_script}

{scan_steps}
"#
    )
}

fn workflow_permissions(upload_sarif: bool) -> &'static str {
    if upload_sarif {
        "  contents: read\n  security-events: write\n  actions: read"
    } else {
        "  contents: read"
    }
}

fn workflow_scan_command(args: &GithubCiArgs) -> String {
    let output_flag = if args.upload_sarif {
        "--sarif"
    } else {
        "--json"
    };
    let mode_flags = match args.mode {
        CiModeArg::Blocking => format!(
            "--fail-on {}",
            args.fail_on.unwrap_or(DEFAULT_FAIL_ON).as_str()
        ),
        CiModeArg::Audit => "--audit".to_string(),
    };

    // `--` keeps a path such as `--help` from being interpreted as a CLI option.
    format!(
        "shk scan {output_flag} {mode_flags} -- {}",
        shell_quote(&args.path)
    )
}

fn workflow_scan_steps(args: &GithubCiArgs) -> String {
    let scan_command = workflow_scan_command(args);
    if args.upload_sarif {
        format!(
            r#"      - name: Run shk
        id: shk_scan
        shell: bash
        run: |
          set -euo pipefail
          set +e
          {scan_command} > "$RUNNER_TEMP/shk-results.sarif"
          SHK_EXIT_CODE=$?
          set -e
          echo "exit_code=$SHK_EXIT_CODE" >> "$GITHUB_OUTPUT"
          if [ "$SHK_EXIT_CODE" -le 1 ] && [ -s "$RUNNER_TEMP/shk-results.sarif" ]; then
            echo "report_ready=true" >> "$GITHUB_OUTPUT"
          else
            echo "report_ready=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload SARIF
        if: ${{{{ always() && steps.shk_scan.outputs.report_ready == 'true' }}}}
        uses: {CODEQL_UPLOAD_ACTION}
        with:
          sarif_file: ${{{{ runner.temp }}}}/shk-results.sarif
          category: shk

      - name: Apply scan result
        if: ${{{{ always() && steps.shk_scan.outputs.exit_code != '' }}}}
        shell: bash
        env:
          SHK_EXIT_CODE: ${{{{ steps.shk_scan.outputs.exit_code }}}}
        run: |
          set -euo pipefail
          if [[ ! "$SHK_EXIT_CODE" =~ ^[0-9]+$ ]]; then
            echo "shk scan did not produce an exit code" >&2
            exit 2
          fi
          exit "$SHK_EXIT_CODE"
"#
        )
    } else {
        format!(
            r#"      - name: Run shk
        shell: bash
        run: |
          {scan_command}
"#
        )
    }
}

/// Download a pinned release archive, verify its checksum, optionally verify GitHub
/// artifact attestation, and install `shk` into `$HOME/.cargo/bin`.
fn verified_install_script(repo: &str, version: &str) -> String {
    let repo_q = shell_quote(repo);
    let version_q = shell_quote(&release_tag(version));
    let latest = version == "latest";
    let download_cmd = if latest {
        format!("gh release download -R {repo_q} -p \"$ASSET\" -p \"${{ASSET}}.sha256\"")
    } else {
        format!(
            "gh release download {version_q} -R {repo_q} -p \"$ASSET\" -p \"${{ASSET}}.sha256\""
        )
    };

    format!(
        r#"          set -euo pipefail
          SHK_VERSION={version_q}
          REPO={repo_q}
          mkdir -p "$HOME/.cargo/bin"
          case "$(uname -s)-$(uname -m)" in
            Linux-x86_64) TARGET=x86_64-unknown-linux-gnu ;;
            Linux-aarch64|Linux-arm64) TARGET=aarch64-unknown-linux-gnu ;;
            Darwin-x86_64) TARGET=x86_64-apple-darwin ;;
            Darwin-arm64) TARGET=aarch64-apple-darwin ;;
            *) echo "unsupported runner: $(uname -s)-$(uname -m)" >&2; exit 1 ;;
          esac
          ASSET="shk-cli-${{TARGET}}.tar.xz"
          {download_cmd}
          sha256sum -c "${{ASSET}}.sha256"
          gh attestation verify "$ASSET" -R "$REPO"
          TMP="$(mktemp -d)"
          tar -xJf "$ASSET" -C "$TMP"
          install -m 755 "$TMP/shk-cli-${{TARGET}}/shk" "$HOME/.cargo/bin/shk"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH""#
    )
}

fn release_tag(version: &str) -> String {
    if version == "latest" || version.starts_with('v') {
        version.to_string()
    } else {
        format!("v{version}")
    }
}

fn shell_quote(s: &str) -> String {
    if !s.is_empty()
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'/' | b'_' | b'-' | b':'))
    {
        return s.to_string();
    }
    format!("'{}'", s.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn args(mode: CiModeArg) -> GithubCiArgs {
        GithubCiArgs {
            mode,
            fail_on: None,
            path: ".".into(),
            repo: "Kazuki-tam/security-harness-kit".into(),
            shk_version: concat!("v", env!("CARGO_PKG_VERSION")).into(),
            upload_sarif: false,
            output: PathBuf::from(".github/workflows/shk.yml"),
            dry_run: false,
            force: false,
        }
    }

    #[test]
    fn github_workflow_uses_verified_release_install() {
        let workflow = github_workflow(&args(CiModeArg::Blocking));
        let expected_version = concat!("v", env!("CARGO_PKG_VERSION"));

        assert!(workflow.contains("gh release download"), "{workflow}");
        assert!(workflow.contains(expected_version), "{workflow}");
        assert!(workflow.contains("sha256sum -c"), "{workflow}");
        assert!(workflow.contains("gh attestation verify"), "{workflow}");
        assert!(
            workflow.contains("shk scan --json --fail-on high -- ."),
            "{workflow}"
        );
        assert!(workflow.contains(CHECKOUT_ACTION), "{workflow}");
        assert!(!workflow.contains("curl --proto"), "{workflow}");
    }

    #[test]
    fn github_workflow_disables_checkout_credential_persistence() {
        let workflow = github_workflow(&args(CiModeArg::Blocking));

        assert!(
            workflow.contains("persist-credentials: false"),
            "{workflow}"
        );
    }

    #[test]
    fn github_workflow_supports_audit_mode() {
        let workflow = github_workflow(&args(CiModeArg::Audit));

        assert!(workflow.contains("shk scan --json --audit -- ."));
        assert!(!workflow.contains("--fail-on"));
    }

    #[test]
    fn github_workflow_emits_minimal_permissions_and_concurrency() {
        let workflow = github_workflow(&args(CiModeArg::Blocking));

        assert!(workflow.contains("permissions:\n  contents: read"));
        assert!(workflow.contains("concurrency:"));
        assert!(workflow.contains("cancel-in-progress: true"));
        assert!(workflow.contains("group: shk-${{ github.workflow }}-${{ github.ref }}"));
    }

    #[test]
    fn github_workflow_can_upload_sarif_before_applying_scan_exit_code() {
        let mut a = args(CiModeArg::Blocking);
        a.upload_sarif = true;
        let workflow = github_workflow(&a);

        assert!(
            workflow.contains("permissions:\n  contents: read\n  security-events: write"),
            "{workflow}"
        );
        assert!(workflow.contains("actions: read"), "{workflow}");
        assert!(
            workflow.contains("shk scan --sarif --fail-on high -- ."),
            "{workflow}"
        );
        assert!(
            workflow.contains("github/codeql-action/upload-sarif@v4"),
            "{workflow}"
        );
        let scan = workflow.find("shk scan --sarif").unwrap();
        let upload = workflow
            .find("github/codeql-action/upload-sarif@v4")
            .unwrap();
        let apply = workflow.find("name: Apply scan result").unwrap();
        assert!(scan < upload && upload < apply, "{workflow}");
        assert!(
            workflow.contains("SHK_EXIT_CODE: ${{ steps.shk_scan.outputs.exit_code }}"),
            "{workflow}"
        );
        assert!(
            workflow.contains("if: ${{ always() && steps.shk_scan.outputs.exit_code != '' }}"),
            "{workflow}"
        );
    }

    #[test]
    fn github_workflow_sarif_audit_mode_remains_non_blocking_for_findings() {
        let mut a = args(CiModeArg::Audit);
        a.upload_sarif = true;
        let workflow = github_workflow(&a);

        assert!(
            workflow.contains("shk scan --sarif --audit -- ."),
            "{workflow}"
        );
        assert!(!workflow.contains("--fail-on"), "{workflow}");
    }

    #[test]
    fn shell_quote_handles_spaces_and_quotes() {
        assert_eq!(shell_quote("src fixtures"), "'src fixtures'");
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn shell_quote_wraps_newline_input_but_validate_rejects_it() {
        // shell_quote on its own would happily produce a multi-line single-quoted string.
        // That is fine for a shell, but it would corrupt the surrounding YAML block scalar,
        // so `validate` must reject newline input before we ever quote it.
        let quoted = shell_quote("src\nevil");
        assert!(quoted.contains('\n'), "{quoted}");

        let mut a = args(CiModeArg::Blocking);
        a.path = "src\nevil".into();
        let err = validate(&a).unwrap_err();
        assert!(err.to_string().contains("must not contain newline"));

        a.path = "src\rdir".into();
        let err = validate(&a).unwrap_err();
        assert!(err.to_string().contains("must not contain newline"));
    }

    #[test]
    fn github_workflow_quotes_path_with_whitespace() {
        let mut a = args(CiModeArg::Blocking);
        a.path = "src dir".into();
        let workflow = github_workflow(&a);
        assert!(
            workflow.contains("shk scan --json --fail-on high -- 'src dir'"),
            "{workflow}"
        );
    }

    #[test]
    fn github_workflow_terminates_options_before_dash_prefixed_path() {
        let mut a = args(CiModeArg::Blocking);
        a.path = "--help".into();

        assert_eq!(
            workflow_scan_command(&a),
            "shk scan --json --fail-on high -- --help"
        );
    }

    #[test]
    fn validate_rejects_unsafe_inputs() {
        let mut a = args(CiModeArg::Blocking);
        a.repo = "not-a-slug".into();
        assert!(validate(&a).is_err());

        let mut a = args(CiModeArg::Blocking);
        a.repo = "../foo".into();
        assert!(
            validate(&a).is_err(),
            "`..` segments must be rejected even when REPO_SLUG_RE matches"
        );

        let mut a = args(CiModeArg::Blocking);
        a.repo = "owner/..".into();
        assert!(validate(&a).is_err());

        let mut a = args(CiModeArg::Blocking);
        a.shk_version = "; rm -rf /".into();
        assert!(validate(&a).is_err());
    }

    #[test]
    fn validate_accepts_canonical_inputs() {
        let mut a = args(CiModeArg::Blocking);
        a.shk_version = "v0.2.3".into();
        assert!(validate(&a).is_ok());
    }
}
