[package]
name = "shk-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Desktop app for Security Harness Kit"
publish = false

[lib]
name = "shk_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "shk-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
shk-cli = { path = "../../../crates/shk-cli" }
shk-core = { version = "0.6.1", path = "../../../crates/shk-core" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
thiserror.workspace = true
tauri-plugin-process = "2"
percent-encoding = "2.3"
tauri-plugin-notification = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"

[dev-dependencies]
tempfile.workspace = true
